language: python
python: 2.7
sudo: false
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  matrix:
    - TOXENV=check
    - TOXENV=2.6-1.4,coveralls
    - TOXENV=2.6-1.4-nocover
    - TOXENV=2.6-1.5,coveralls
    - TOXENV=2.6-1.5-nocover
    - TOXENV=2.6-1.6,coveralls
    - TOXENV=2.6-1.6-nocover
    - TOXENV=2.7-1.4,coveralls
    - TOXENV=2.7-1.4-nocover
    - TOXENV=2.7-1.5,coveralls
    - TOXENV=2.7-1.5-nocover
    - TOXENV=2.7-1.6,coveralls
    - TOXENV=2.7-1.6-nocover
    - TOXENV=2.7-1.7,coveralls
    - TOXENV=2.7-1.7-nocover
    - TOXENV=2.7-1.8,coveralls
    - TOXENV=2.7-1.8-nocover
    - TOXENV=3.3-1.5,coveralls
    - TOXENV=3.3-1.5-nocover
    - TOXENV=3.3-1.6,coveralls
    - TOXENV=3.3-1.6-nocover
    - TOXENV=3.3-1.7,coveralls
    - TOXENV=3.3-1.7-nocover
    - TOXENV=3.3-1.8,coveralls
    - TOXENV=3.3-1.8-nocover
    - TOXENV=3.4-1.5,coveralls
    - TOXENV=3.4-1.5-nocover
    - TOXENV=3.4-1.6,coveralls
    - TOXENV=3.4-1.6-nocover
    - TOXENV=3.4-1.7,coveralls
    - TOXENV=3.4-1.7-nocover
    - TOXENV=3.4-1.8,coveralls
    - TOXENV=3.4-1.8-nocover
    - TOXENV=pypy-1.4,coveralls
    - TOXENV=pypy-1.4-nocover
    - TOXENV=pypy-1.5,coveralls
    - TOXENV=pypy-1.5-nocover
    - TOXENV=pypy-1.6,coveralls
    - TOXENV=pypy-1.6-nocover
    - TOXENV=pypy-1.7,coveralls
    - TOXENV=pypy-1.7-nocover
    - TOXENV=pypy-1.8,coveralls
    - TOXENV=pypy-1.8-nocover
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - pip install tox
script:
  - tox -v
notifications:
  email:
    on_success: never
    on_failure: always

