language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
env:
  global:
    PYTHONPATH=src:tests
    PYTHONUNBUFFERED=yes
  matrix:
    - DJANGO_VERSION=1.1
    - DJANGO_VERSION=1.2
    - DJANGO_VERSION=1.3
    - DJANGO_VERSION=1.4
    - DJANGO_VERSION=1.5
    - DJANGO_VERSION=1.6
    - DJANGO_VERSION=1.7
matrix:
  allow_failures:
    - env: DJANGO_VERSION=1.1
      python: 3.3
    - env: DJANGO_VERSION=1.1
      python: 3.2
    - env: DJANGO_VERSION=1.2
      python: 3.3
    - env: DJANGO_VERSION=1.2
      python: 3.2
    - env: DJANGO_VERSION=1.3
      python: 3.3
    - env: DJANGO_VERSION=1.3
      python: 3.2
    - env: DJANGO_VERSION=1.4
      python: 3.3
    - env: DJANGO_VERSION=1.4
      python: 3.2
    - env: DJANGO_VERSION=1.7
      python: 2.6
before_install:
  - |
    deactivate
    if python --version |& grep PyPy; then
      sudo apt-add-repository --yes ppa:pypy/ppa
      sudo apt-get update
      sudo apt-get install pypy
      source ~/virtualenv/pypy/bin/activate
    fi
    python --version
    uname -a
    lsb_release -a
    sudo pip install tox
script: tox -v -e $TRAVIS_PYTHON_VERSION-$DJANGO_VERSION
after_success:
  - .tox/$TRAVIS_PYTHON_VERSION-$DJANGO_VERSION/bin/coveralls
notifications:
  email:
    on_success: never
    on_failure: always