language: python
python:
  - 2.6
  - 2.7
  - pypy
env:
  global:
    PYTHONPATH=src:tests
    PYTHONUNBUFFERED=yes
  matrix:
    - DJANGO_VERSION=1.3
    - DJANGO_VERSION=1.4
    - DJANGO_VERSION=1.5
    - DJANGO_VERSION=1.6
    - DJANGO_VERSION=trunk
matrix:
  allow_failures:
    - env: DJANGO_VERSION=trunk
      python: pypy
before_install:
  - |
    deactivate
    if python --version |& grep PyPy; then
      sudo apt-add-repository --yes ppa:pypy/ppa
      sudo apt-get update
      sudo apt-get install pypy
      source ~/virtualenv/pypy/bin/activate
    fi
    python --version
    uname -a
    lsb_release -a
    sudo pip install tox
script: tox -v -e $TRAVIS_PYTHON_VERSION-$DJANGO_VERSION
after_success:
  - coverage combine || true
  - coverage report --show-missing --include='src/*' || true
  - coveralls || true
