name: build
on: [push, pull_request]
jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'check'
            python: '3.9'
            toxpython: 'python3.9'
            tox_env: 'check'
            os: 'ubuntu-latest'
          - name: 'docs'
            python: '3.9'
            toxpython: 'python3.9'
            tox_env: 'docs'
            os: 'ubuntu-latest'
          - name: 'py36-dj32 (ubuntu)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-dj32'
            os: 'ubuntu-latest'
          - name: 'py36-dj40 (ubuntu)'
            python: '3.6'
            toxpython: 'python3.6'
            python_arch: 'x64'
            tox_env: 'py36-dj40'
            os: 'ubuntu-latest'
          - name: 'py37-dj32 (ubuntu)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-dj32'
            os: 'ubuntu-latest'
          - name: 'py37-dj40 (ubuntu)'
            python: '3.7'
            toxpython: 'python3.7'
            python_arch: 'x64'
            tox_env: 'py37-dj40'
            os: 'ubuntu-latest'
          - name: 'py38-dj32 (ubuntu)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-dj32'
            os: 'ubuntu-latest'
          - name: 'py38-dj40 (ubuntu)'
            python: '3.8'
            toxpython: 'python3.8'
            python_arch: 'x64'
            tox_env: 'py38-dj40'
            os: 'ubuntu-latest'
          - name: 'py39-dj32 (ubuntu)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-dj32'
            os: 'ubuntu-latest'
          - name: 'py39-dj40 (ubuntu)'
            python: '3.9'
            toxpython: 'python3.9'
            python_arch: 'x64'
            tox_env: 'py39-dj40'
            os: 'ubuntu-latest'
          - name: 'py310-dj32 (ubuntu)'
            python: '3.10'
            toxpython: 'python3.10'
            python_arch: 'x64'
            tox_env: 'py310-dj32'
            os: 'ubuntu-latest'
          - name: 'py310-dj40 (ubuntu)'
            python: '3.10'
            toxpython: 'python3.10'
            python_arch: 'x64'
            tox_env: 'py310-dj40'
            os: 'ubuntu-latest'
          - name: 'pypy37-dj32 (ubuntu)'
            python: 'pypy-3.7'
            toxpython: 'pypy3.7'
            python_arch: 'x64'
            tox_env: 'pypy37-dj32'
            os: 'ubuntu-latest'
          - name: 'pypy37-dj40 (ubuntu)'
            python: 'pypy-3.7'
            toxpython: 'pypy3.7'
            python_arch: 'x64'
            tox_env: 'pypy37-dj40'
            os: 'ubuntu-latest'
          - name: 'pypy38-dj32 (ubuntu)'
            python: 'pypy-3.8'
            toxpython: 'pypy3.8'
            python_arch: 'x64'
            tox_env: 'pypy38-dj32'
            os: 'ubuntu-latest'
          - name: 'pypy38-dj40 (ubuntu)'
            python: 'pypy-3.8'
            toxpython: 'pypy3.8'
            python_arch: 'x64'
            tox_env: 'pypy38-dj40'
            os: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.python_arch }}
    - name: install dependencies
      run: |
        python -mpip install --progress-bar=off -r ci/requirements.txt
        virtualenv --version
        pip --version
        tox --version
        pip list --format=freeze
    - name: test
      env:
        TOXPYTHON: '${{ matrix.toxpython }}'
      run: >
        tox -e ${{ matrix.tox_env }} -v
